remove trunc_normal for model.head.weight since weights are initalized in the decoder module
try to fix "AttributeError: 'Decoder' object has no attribute 'weight'"